sudo: false
language: python
python:
  - 3.6
  - 3.5
  - 2.7
matrix:
  fast_finish: true
before_install:
  - pip install flake8 black
  - flake8
  - black . --check
install:
  - pip install tox-travis
  - pip install coveralls
script:
  - tox
after_success:
  - coveralls
